# Generated by Django 4.0.4 on 2024-02-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_user_alter_pharmacyproduct_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='price_per_pack',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='price_per_sheet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='quantity_other',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='sheets_per_pack',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pharmacyproduct',
            name='tablets_per_sheet',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
