# Generated by Django 4.0.4 on 2024-02-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_pharmacyproduct_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyproduct',
            old_name='quantity_other',
            new_name='quantity',
        ),
    ]
